stations:
  - id: EVB-P17390866
    evse:
      count: 1
      connectors: 1
    componentsConfiguration:
      security:
        basicAuthPassword: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      tx:
        evConnectionTimeOutSec: 120
  - id: EVB-P18090564
    evse:
      count: 2
      connectors: 1
    componentsConfiguration:
      security:
        basicAuthPassword: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      tx:
        evConnectionTimeOutSec: 60