stations:
  - id: EVB-P17390866
    evse:
      count: 1
      connectors: 1
    componentsConfiguration:
      securityCtrlr:
        basicAuthPassword: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      txCtrlr:
        evConnectionTimeOutSec: 120
        txStartPoint:
          - EVConnected
          - Authorized
        txStopPoint:
          - Authorized
  - id: EVB-P18090564
    evse:
      count: 2
      connectors: 1
    componentsConfiguration:
      securityCtrlr:
        basicAuthPassword: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      txCtrlr:
        evConnectionTimeOutSec: 60